# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 10:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='client_name')),
                ('phone', models.CharField(blank=True, max_length=45, null=True, verbose_name='phone')),
                ('memo', models.CharField(blank=True, max_length=300, null=True, verbose_name='memo')),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='debt')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='photo')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
            },
        ),
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveIntegerField(choices=[(1, 'My debt'), (2, 'Client debt'), (3, 'Sell debt')], default=1, verbose_name='debt_type')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='total')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='amount')),
                ('v_date', models.DateField(default=datetime.date.today, verbose_name='date')),
                ('v_timestamp', models.DateTimeField(auto_now_add=True)),
                ('m_timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'general',
                'verbose_name_plural': 'generals',
            },
        ),
        migrations.CreateModel(
            name='MainInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='total')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='discount')),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='debt')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='amount')),
                ('v_date', models.DateField(default=datetime.date.today, verbose_name='date')),
                ('memo', models.CharField(blank=True, max_length=300, null=True, verbose_name='memo')),
                ('v_timestamp', models.DateTimeField(auto_now_add=True)),
                ('m_timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainSell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_count', models.IntegerField(default=0)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('v_date', models.DateField(default=datetime.date.today)),
                ('v_timestamp', models.DateTimeField(auto_now_add=True)),
                ('m_timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
            options={
                'verbose_name': 'part',
                'verbose_name_plural': 'parts',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_income', models.IntegerField(default=0)),
                ('p_outgo', models.IntegerField(default=0)),
                ('p_sell', models.IntegerField(default=0)),
                ('p_count', models.IntegerField(default=0)),
                ('s_sum', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('m_timestamp', models.DateTimeField(auto_now=True)),
                ('part', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.Part')),
            ],
            options={
                'verbose_name': 'part on store',
                'verbose_name_plural': 'parts on store',
            },
        ),
        migrations.CreateModel(
            name='ClientDebt',
            fields=[
                ('general_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.General')),
            ],
            options={
                'verbose_name': 'client debt',
                'verbose_name_plural': 'client debts',
            },
            bases=('store.general',),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('maininvoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.MainInvoice')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Client', verbose_name='client')),
            ],
            options={
                'verbose_name': 'direct delivery',
                'verbose_name_plural': 'direct deliveries',
            },
            bases=('store.maininvoice',),
        ),
        migrations.CreateModel(
            name='DeliveryAmount',
            fields=[
                ('general_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.General')),
            ],
            options={
                'verbose_name': 'delivery amount',
                'verbose_name_plural': 'delivery amounts',
            },
            bases=('store.general',),
        ),
        migrations.CreateModel(
            name='DeliveryPart',
            fields=[
                ('mainsell_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.MainSell')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Delivery')),
            ],
            bases=('store.mainsell',),
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('maininvoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.MainInvoice')),
            ],
            options={
                'verbose_name': 'delivery to store',
                'verbose_name_plural': 'deliveries to store',
            },
            bases=('store.maininvoice',),
        ),
        migrations.CreateModel(
            name='IncomeAmount',
            fields=[
                ('general_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.General')),
            ],
            options={
                'verbose_name': 'income amount',
                'verbose_name_plural': 'income amounts',
            },
            bases=('store.general',),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('maininvoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.MainInvoice')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Client', verbose_name='client')),
            ],
            options={
                'verbose_name': 'sell from store',
                'verbose_name_plural': 'sales from store',
            },
            bases=('store.maininvoice',),
        ),
        migrations.CreateModel(
            name='InvoiceOut',
            fields=[
                ('mainsell_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.MainSell')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Invoice')),
            ],
            bases=('store.mainsell',),
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('maininvoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.MainInvoice')),
            ],
            options={
                'verbose_name': 'sell from shop',
                'verbose_name_plural': 'sales from shop',
            },
            bases=('store.maininvoice',),
        ),
        migrations.CreateModel(
            name='SellDebt',
            fields=[
                ('general_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.General')),
                ('debt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.Sell', verbose_name='debt')),
            ],
            options={
                'verbose_name': 'sell debt',
                'verbose_name_plural': 'sell debts',
            },
            bases=('store.general',),
        ),
        migrations.CreateModel(
            name='StoreIncome',
            fields=[
                ('mainsell_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.MainSell')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Income')),
            ],
            bases=('store.mainsell',),
        ),
        migrations.CreateModel(
            name='StoreSell',
            fields=[
                ('mainsell_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.MainSell')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Sell')),
            ],
            bases=('store.mainsell',),
        ),
        migrations.AddField(
            model_name='mainsell',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainsell', to='store.Part'),
        ),
        migrations.CreateModel(
            name='ClientDeliveryDebt',
            fields=[
                ('clientdebt_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.ClientDebt')),
                ('debt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.Delivery', verbose_name='debt')),
            ],
            options={
                'verbose_name': 'client debt for delivery',
                'verbose_name_plural': 'client debts for delivery',
            },
            bases=('store.clientdebt',),
        ),
        migrations.CreateModel(
            name='ClientInvoiceDebt',
            fields=[
                ('clientdebt_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.ClientDebt')),
                ('debt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.Invoice', verbose_name='debt')),
            ],
            options={
                'verbose_name': 'client debt for invoice',
                'verbose_name_plural': 'client debts for invoice',
            },
            bases=('store.clientdebt',),
        ),
        migrations.CreateModel(
            name='DeliveryDebt',
            fields=[
                ('deliveryamount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.DeliveryAmount')),
                ('debt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.Delivery', verbose_name='debt')),
            ],
            options={
                'verbose_name': 'delivery debt',
                'verbose_name_plural': 'delivery debts',
            },
            bases=('store.deliveryamount',),
        ),
        migrations.CreateModel(
            name='IncomeDebt',
            fields=[
                ('incomeamount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.IncomeAmount')),
                ('debt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.Income', verbose_name='debt')),
            ],
            options={
                'verbose_name': 'income debt',
                'verbose_name_plural': 'income debts',
            },
            bases=('store.incomeamount',),
        ),
        migrations.AddField(
            model_name='clientdebt',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Client', verbose_name='client'),
        ),
    ]
